"""
https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        print (s, t)
        list1 = []
        list1[:0] = t
        print (t)
        for i in s:
            print (i)
            list1.remove(i)
        return list1[0]


class Solution3:
    def findTheDifference(self, s: str, t: str) -> str:
        return list((Counter(t) - Counter(s)).keys())[0]


class Solution2:
    def findTheDifference(self, s: str, t: str) -> str:
        res = 0
        for letter in s:
            # print (ord(letter))
            res ^= ord(letter)
            # print (res)
        # print (res)
        for letter in t:
            res ^= ord(letter)
        # print (res)

        return chr(res)



if __name__ == '__main__':
    s = "abcd"
    t = "abcde"
    print ("CASE 1 : S : {}, T : {}".format(s, t))
    sol = Solution().findTheDifference(s, t)
    print ("Solution : {}".format(sol))